### ISSUE TITLE
测试发现，文本组件输入泰语不生效

### ISSUE THREAD

**Issue by xqb0407** [psoho/fastposter-client-java#1]
![image](https://github.com/user-attachments/assets/60450de7-d6e8-4b44-ae7f-3c1cff2d0e62)
![image](https://github.com/user-attachments/assets/0591be83-0973-4f34-b7ea-889d4e391d25)

**Comment by tangweixin** [comment]
这是字体问题，需要对应的泰语字体才支持哦
